on:
  push:
    branches:
      - main

jobs:
  trigger_ab_test:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger Buildkite Pipeline"
        run: |
          curl -X POST https://api.buildkite.com/v2/organizations/firecracker/pipelines/roypat-collect-cascake-lake-baselines/builds \
               -H 'Content-Type: application/json' \
               -H 'Authorization: Bearer ${{ secrets.BUILDKITE_TOKEN }}' \
               -d '{
                    "commit": "HEAD",
                    "branch": "${{ github.event.push.ref }}",
                    "env": {
                      "REVISION_A": "${{ github.event.push.before }}",
                      "REVISION_B": "${{ github.event.push.after }}",
                    },
                  }'